### ISSUE TITLE
Can't reprocduce the result in README

### ISSUE THREAD

**Issue by StanislavNikolov** [thcipriani/slime-bishop#1]
Running slime-coins.py with Python 2.7.13 works, but shows different image that the one in the .gif. Also, one must press Ctrl+D to enter the string, it does not stop on \n.
```
$ python slime-coins.py -e
b2c72a77843a629756d0954963fd5d2b
ab0ee69d3f9da9c1258eda7eb75247d3
+-----------------+
|                 |
|                 |
|             .   |
|            o E  |
|        S .. .   |
|       + +. .    |
|    o . =o +     |
|   o = o+.=      |
|    ooBoo=..     |
+-----------------+
$ echo "b2c72a77843a629756d0954963fd5d2b" > t
$ python slime-coins.py -e < t
ab0ee69d3f9da9c1258eda7eb75247d3
+-----------------+
|                 |
|                 |
|             .   |
|            o E  |
|        S .. .   |
|       + +. .    |
|    o . =o +     |
|   o = o+.=      |
|    ooBoo=..     |
+-----------------+

```
Python 3.5.4 crashes while parsing the input:
```
$ python3 slime-coins.py -e < t
Traceback (most recent call last):
  File "/usr/lib/python3.5/base64.py", line 518, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "slime-coins.py", line 232, in <module>
    base = base64.decodestring(base)
  File "/usr/lib/python3.5/base64.py", line 562, in decodestring
    return decodebytes(s)
  File "/usr/lib/python3.5/base64.py", line 553, in decodebytes
    _input_type_check(s)
  File "/usr/lib/python3.5/base64.py", line 521, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
```

**Comment by thcipriani** [comment]
> Running slime-coins.py with Python 2.7.13 works, but shows different image that the one in the .gif. 

Unless you have my public key the image produced should differ, this is the way in which you can differentiate different inputs. For each unique input, the output should also be unique.

> Also, one must press Ctrl+D to enter the string, it does not stop on \n.

This is normal behavior for reading from stdin in my experience. If you pipe to the program, that should work fine.

> Python 3.5.4 crashes

This should be fixed by 4eb60de please reopen this issue if you find that is not the case.

Thanks for the issue report @StanislavNikolov !

**Comment by StanislavNikolov** [comment]
> Unless you have my public key the image produced should differ, this is the way in which you can differentiate different inputs. For each unique input, the output should also be unique.

I don't understand. You are trying to say that the contents of .ssh/ change the output? The script just takes the first line of stdin and uses it to generate the image, doesn't it? As you can see in the log, I enter absolutely the same input (which, if I understand correctly, is the MD5 hash of your public key), so I should get the same output. Maybe it reads some special control character or I don't understand exactly how it works.

As no one else has reported the same problem, I assume it's the latter.

P.S:
Thanks for the Python 3 fiх :D

**Comment by StanislavNikolov** [comment]
Well, I just tried it and now it does not work neither in python2 nor in python3 :(

```
$ python2 slime-coins.py -e < t
Traceback (most recent call last):
  File "slime-coins.py", line 232, in <module>
    base = base64.decodestring(bytes(base, 'utf-8'))
TypeError: str() takes at most 1 argument (2 given)
```

Python 3 does not crash, just produces empty image.
```
$ python3 slime-coins.py -e -s 0.25 < t
ab0ee69d3f9da9c1258eda7eb75247d3
+-----------------+
|                 |
|                 |
|                 |
|                 |
|                 |
|                 |
|                 |
|                 |
|                 |
+-----------------+
```

Removing the -e makes python3 crash and python2 work, but with yet another different output (that is expected of course)
```
$ python3 slime-coins.py < t
Traceback (most recent call last):
  File "slime-coins.py", line 234, in <module>
    md5 = md5sum(base)
  File "slime-coins.py", line 93, in md5sum
    m.update(datum)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by thcipriani** [comment]
@StanislavNikolov what is the content of `t` in your examples?

**Comment by StanislavNikolov** [comment]
```
$ cat t
b2c72a77843a629756d0954963fd5d2b
```
Taken from https://tylercipriani.com/blog/2017/09/26/ssh-key-fingerprints-identicons-and-ascii-art/

**Comment by thcipriani** [comment]
@StanislavNikolov this time, I think I really got the python2/3 stuff worked out :)

```
slime-bishop (master * u=)                                                                                                                                               
(/^ヮ^)/*:・ﾟ✧ python2 --version                                                                                                                                         
Python 2.7.13                                                                                                                                                            
slime-bishop (master * u=)                                                                                                                                               
(/^ヮ^)/*:・ﾟ✧ python3 --version                                                                                                                                         
Python 3.5.4     
```

```
slime-bishop (master * u=)                                                                                                                                               
(/^ヮ^)/*:・ﾟ✧ printf 'b2c72a77843a629756d0954963fd5d2b' | python2 slime-coins.py -s 0                                                                                   
802b484683b193600384c18bea9e8651                                                                                                                                         
+-----------------+                                                                                                                                                      
|@O               |                                                                                                                                                      
|*+o  .           |                                                                                                                                                      
|=o. . .          |                                                                                                                                                      
|++E  . .         |                                                                                                                                                      
|o.. .   S        |                                                                                                                                                      
|o  .             |                                                                                                                                                      
|o.               |                                                                                                                                                      
|.o.              |                                                                                                                                                      
|oo               |                                                                                                                                                      
+-----------------+                                                                                                                                                      
slime-bishop (master * u=)                                                                                                                                               
(/^ヮ^)/*:・ﾟ✧ printf 'b2c72a77843a629756d0954963fd5d2b' | python3 slime-coins.py -s 0                                                                                   
802b484683b193600384c18bea9e8651                                                                                                                                         
+-----------------+                                                                                                                                                      
|@O               |                                                                                                                                                      
|*+o  .           |                                                                                                                                                      
|=o. . .          |                                                                                                                                                      
|++E  . .         |                                                                                                                                                      
|o.. .   S        |                                                                                                                                                      
|o  .             |                                                                                                                                                      
|o.               |                                                                                                                                                      
|.o.              |                                                                                                                                                      
|oo               |                                                                                                                                                      
+-----------------+                                                                                                                                                      
slime-bishop (master * u=)                                                                                                                                               
(/^ヮ^)/*:・ﾟ✧ printf 'b2c72a77843a629756d0954963fd5d2b' | python3 slime-coins.py -s 0 -c -b                                                                             
802b484683b193600384c18bea9e8651                                                                                                                                         
+-----------------+                                                                                                                                                      
|▛▚               |                                                                                                                                                      
|▄▓▒  ░           |                                                                                                                                                      
|▂▒░ ░ ░          |                                                                                                                                                      
|▓▓E  ░ ░         |                                                                                                                                                      
|▒░░ ░   S        |                                                                                                                                                      
|▒  ░             |                                                                                                                                                      
|▒░               |                                                                                                                                                      
|░▒░              |                                                                                                                                                      
|▒▒               |                                                                                                                                                      
+-----------------+               
```

```
(/^ヮ^)/*:・ﾟ✧ awk '{print $2}' ~/.ssh/id_rsa.old.pub | python3 slime-coins.py -e -s 0                                                                                   
b2c72a77843a629756d0954963fd5d2b                                                                                                                                         
+-----------------+                                                                                                                                                      
|       .++       |                                                                                                                                                      
|       .+..     .|                                                                                                                                                      
|     . .   . . ..|                                                                                                                                                      
|    . .     .E.. |                                                                                                                                                      
|     ...S     .  |                                                                                                                                                      
|      o+.        |                                                                                                                                                      
|     +..o        |                                                                                                                                                      
|  o B .o.        |                                                                                                                                                      
| . + +..         |                                                                                                                                                      
+-----------------+                                                                                                                                                      
slime-bishop (master * u=)                                                                                                                                               
(/^ヮ^)/*:・ﾟ✧ awk '{print $2}' ~/.ssh/id_rsa.old.pub | python2 slime-coins.py -e -s 0                                                                                   
b2c72a77843a629756d0954963fd5d2b                                                                                                                                         
+-----------------+                                                                                                                                                      
|       .++       |                                                                                                                                                      
|       .+..     .|                                                                                                                                                      
|     . .   . . ..|                                                                                                                                                      
|    . .     .E.. |                                                                                                                                                      
|     ...S     .  |                                                                                                                                                      
|      o+.        |                                                                                                                                                      
|     +..o        |                                                                                                                                                      
|  o B .o.        |                                                                                                                                                      
| . + +..         |                                                                                                                                                      
+-----------------+                                                                                                                                                      
slime-bishop (master * u=)                                                                                                                                               
(/^ヮ^)/*:・ﾟ✧ ssh-keygen -lv -Emd5 -f ~/.ssh/id_rsa.old.pub                                                                                                             
2048 MD5:b2:c7:2a:77:84:3a:62:97:56:d0:95:49:63:fd:5d:2b tyler@tylercipriani.com (RSA)                                                                                   
+---[RSA 2048]----+                                                                                                                                                      
|       .++       |                                                                                                                                                      
|       .+..     .|                                                                                                                                                      
|     . .   . . ..|                                                                                                                                                      
|    . .     .E.. |                                                                                                                                                      
|     ...S     .  |                                                                                                                                                      
|      o+.        |                                                                                                                                                      
|     +..o        |                                                                                                                                                      
|  o B .o.        |                                                                                                                                                      
| . + +..         |       
+------[MD5]------+                                                                                                                                                      
```

**Comment by thcipriani** [comment]
>> Unless you have my public key the image produced should differ, this is the way in which you can differentiate different inputs. For each unique input, the output should also be unique.

> I don't understand. You are trying to say that the contents of .ssh/ change the output? The script just takes the first line of stdin and uses it to generate the image, doesn't it? As you can see in the log, I enter absolutely the same input (which, if I understand correctly, is the MD5 hash of your public key), so I should get the same output. Maybe it reads some special control character or I don't understand exactly how it works.

In your log it looks like you are entering `b2c72a77843a629756d0954963fd5d2b` which is the md5sum of the public key I used to generate the readme. You are also passing `-e` which base64 decodes it. This gives you the md5sum `ab0ee69d3f9da9c1258eda7eb75247d3`

```
slime-bishop (master % u=)
(/^ヮ^)/*:・ﾟ✧ printf 'b2c72a77843a629756d0954963fd5d2b' | base64 --decode | md5sum
ab0ee69d3f9da9c1258eda7eb75247d3  -
```

Given the input you used, I get the output you got:

```
slime-bishop (master % u=)
(/^ヮ^)/*:・ﾟ✧ echo 'b2c72a77843a629756d0954963fd5d2b' | python3 slime-coins.py -s 0 -e
ab0ee69d3f9da9c1258eda7eb75247d3
+-----------------+
|                 |
|                 |
|             .   |
|            o E  |
|        S .. .   |
|       + +. .    |
|    o . =o +     |
|   o = o+.=      |
|    ooBoo=..     |
+-----------------+
```

Had you used: `AAAAB3NzaC1yc2EAAAADAQABAAABAQDNuuN/+/SHRPkC+7P7Vm6CdTFp5k8hp6GtKV+EUkCBGDpkfmhEkLnUKZFg/Jeb/gfPfJm6aleVkyd18IhwSK55g6VQ3VgeloG5ZjB/H9D4ilPYzpxEaXJydgpC6e3zCJdkdmDH1XktuIczZgornEm/06b2huhjLxTdbA7yr/FX5i0q6kqeoU6co6kM47c1goBf2MmHmoYI0fE8fGwbQKlvXcITZtX1UM7AkUyfDQtj3uaHL/PDcsF14paBLUx3iS3flu7ynUBiSekrOKQvYbW0EtPDE8FP3noMiuLXrrzR0Fht1iKTGuIlamJnTU0ciR/Ro4FPj+HN5WBnzXRKjG2H` (which is the content of an old public key of mine that I used in the post) as input, you would have gotten the output from the readme:

```
slime-bishop (master % u=)
(/^ヮ^)/*:・ﾟ✧ printf 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDNuuN/+/SHRPkC+7P7Vm6CdTFp5k8hp6GtKV+EUkCBGDpkfmhEkLnUKZFg/Jeb/gfPfJm6aleVkyd18IhwSK55g6VQ3VgeloG5ZjB/H9D4ilPYzpxEaXJydgpC6e3zCJdkdmDH1XktuIczZgornEm/06b2huhjLxTdbA7yr/FX5i0q6kqeoU6co6kM47c1goBf2MmHmoYI0fE8fGwbQKlvXcITZtX1UM7AkUyfDQtj3uaHL/PDcsF14paBLUx3iS3flu7ynUBiSekrOKQvYbW0EtPDE8FP3noMiuLXrrzR0Fht1iKTGuIlamJnTU0ciR/Ro4FPj+HN5WBnzXRKjG2H' | base64 --decode | md5sum
b2c72a77843a629756d0954963fd5d2b  -
slime-bishop (master % u=)
(/^ヮ^)/*:・ﾟ✧ printf 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDNuuN/+/SHRPkC+7P7Vm6CdTFp5k8hp6GtKV+EUkCBGDpkfmhEkLnUKZFg/Jeb/gfPfJm6aleVkyd18IhwSK55g6VQ3VgeloG5ZjB/H9D4ilPYzpxEaXJydgpC6e3zCJdkdmDH1XktuIczZgornEm/06b2huhjLxTdbA7yr/FX5i0q6kqeoU6co6kM47c1goBf2MmHmoYI0fE8fGwbQKlvXcITZtX1UM7AkUyfDQtj3uaHL/PDcsF14paBLUx3iS3flu7ynUBiSekrOKQvYbW0EtPDE8FP3noMiuLXrrzR0Fht1iKTGuIlamJnTU0ciR/Ro4FPj+HN5WBnzXRKjG2H' | python slime-coins.py -s0 -e                                                                                  
b2c72a77843a629756d0954963fd5d2b                                                                                                                                         
+-----------------+                                                                                                                                                      
|       .++       |                                                                                                                                                      
|       .+..     .|                                                                                                                                                      
|     . .   . . ..|                                                                                                                                                      
|    . .     .E.. |                                                                                                                                                      
|     ...S     .  |                                                                                                                                                      
|      o+.        |                                                                                                                                                      
|     +..o        |                                                                                                                                                      
|  o B .o.        |                                                                                                                                                      
| . + +..         |                                                                                                                                                      
+-----------------+                                   
```

**Comment by thcipriani** [comment]
@StanislavNikolov reopen if this is still failing for you. I may actually have to write some tests :P
